#!/usr/bin/env python3
"""
TiRexOnlyStrategy - SAGE-Forge NT-Native Strategy

Generated by SAGE-Forge CLI - Professional trading strategy template.
"""

from decimal import Decimal
from nautilus_trader.model.data import Bar
from nautilus_trader.model.enums import OrderSide
from nautilus_trader.trading.strategy import Strategy
from rich.console import Console

from sage_forge.core.config import get_config
from sage_forge.risk.position_sizer import RealisticPositionSizer

console = Console()


class TiRexOnlyStrategy(Strategy):
    """
    Professional NT-native strategy generated by SAGE-Forge CLI.
    
    Features:
    - Full NautilusTrader compliance
    - Professional risk management
    - Self-contained dependencies
    """
    
    def __init__(self, config):
        super().__init__(config)
        
        # SAGE-Forge configuration
        self.sage_config = get_config()
        
        # Professional position sizing
        self.position_sizer = RealisticPositionSizer()
        
        # Strategy parameters
        self.fast_period = config.fast_period
        self.slow_period = config.slow_period
        
    def on_start(self):
        """Initialize strategy."""
        self.subscribe_bars(self.config.bar_type)
        console.log(f"🚀 {name} strategy started")
        
    def on_bar(self, bar: Bar):
        """Process new bar data."""
        # Implement your trading logic here
        
        # Example: Get position size
        position_size = self.position_sizer.get_recommended_position_size()
        
        # Example: Create order
        # order = self.order_factory.market(
        #     instrument_id=bar.bar_type.instrument_id,
        #     order_side=OrderSide.BUY,
        #     quantity=position_size
        # )
        # self.submit_order(order)
        
        pass
        
    def on_stop(self):
        """Strategy shutdown."""
        console.log(f"⏹️ {name} strategy stopped")
